# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170729_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lnglat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
